#ifndef UDSM_INTERFACE
#define UDSM_INTERFACE
/*ENUME CONTENT THE SESSION */



void UDSM_voidInit(void);          //FUNCTION TO INIATE UDS MANAGER
void UDSM_voidResponse(void);      //FUNCTION TO MAKE UDS PROCESS THE MASSAGE AND SEND THE RESPOSE
void UDSM_voidRecieveAsy(volatile u8* ptr);  //TO TAKE THE FLAG WILL RISE WHEN RECEIVE DATA IN CAN TO POLL IN IT
#endif
